global:
   external_labels:
       monitor: 'devops-monitor'

scrape_configs:
  - job_name: 'devops'
    scrape_interval: 5s
    static_configs: 
       - targets: ['prometheus:9090','cadvisor:8080','node_exporter:9100','elasticsearch-exporter:9108']
  - job_name: 'rabbitmq'
    scrape_interval: 5s
    metrics_path: /api/metrics
    static_configs:
       - targets: ['rabbitmq:15672']